### ISSUE TITLE
Creating a folder should select it

### ISSUE THREAD

**Issue by cdsmith** [google/codeworld#527]
This confuses people.  When they create a new folder, they expect it to be selected for them automatically.

@parvmor

**Comment by parvmor** [comment]
This was corrected with #523.

**Comment by cdsmith** [comment]
Is that in a pull request that you intend to send in the future?  This is definitely still broken at HEAD.

**Comment by parvmor** [comment]
Yes, I will send it soon!
